apiVersion: v1
kind: Secret
metadata:
  name: ontop-secrets
  namespace: ontop-ui
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: lvfa_db
  LLM_API_KEY: lm-studio
